# Generated by Django 2.2.4 on 2021-01-27 18:13

from django.db import migrations


def transfering_data_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owner_phone_pure=flat.owner_pure_phone,
            defaults={
                'owner_phonenumber': flat.owners_phonenumber,
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210127_2048'),
    ]

    operations = [
        migrations.RunPython(transfering_data_to_owner),
    ]
