# Generated by Django 2.2.4 on 2021-01-27 19:55

from django.db import migrations


def connect_owner_flat(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owners = Owner.objects.filter(
            owner=flat.owner,
            owner_phonenumber=flat.owners_phonenumber
        )
        flat.owners.set(owners)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210127_2113'),
    ]

    operations = [
        migrations.RunPython(connect_owner_flat),
    ]
